// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [
      TSubRelationship in Extract<
        TRelationship["fields"][number],
        prismic.CustomTypeModelFetchContentRelationshipLevel1
      > as TSubRelationship["id"]
    ]: ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
  } & // Group
  {
    [
      TGroup in Extract<
        TRelationship["fields"][number],
        | prismic.CustomTypeModelFetchGroupLevel1
        | prismic.CustomTypeModelFetchGroupLevel2
      > as TGroup["id"]
    ]: TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [
      TFieldKey in Extract<TRelationship["fields"][number], string>
    ]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [
    ID in Exclude<TCustomType[number], string>["id"]
  ]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PartnerPageDocumentDataSlicesSlice = PartnerProgramSlice | HeroSlice;

/**
 * Content for partner_page documents
 */
interface PartnerPageDocumentData {
  /**
   * Slice Zone field in *partner_page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PartnerPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *partner_page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eddyson partner
   * - **API ID Path**: partner_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *partner_page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Your partner in the EDI jungle
   * - **API ID Path**: partner_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *partner_page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * partner_page document from Prismic
 *
 * - **API ID**: `partner_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PartnerPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PartnerPageDocumentData>,
    "partner_page",
    Lang
  >;

export type AllDocumentTypes = PartnerPageDocument;

/**
 * Item in *BenefitsGrid → Default → Primary → Cards*
 */
export interface BenefitsGridSliceDefaultPrimaryCardsItem {
  /**
   * image field in *BenefitsGrid → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits_grid.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Headline field in *BenefitsGrid → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits_grid.default.primary.cards[].headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Copy field in *BenefitsGrid → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits_grid.default.primary.cards[].copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copy: prismic.RichTextField;
}

/**
 * Primary content in *BenefitsGrid → Default → Primary*
 */
export interface BenefitsGridSliceDefaultPrimary {
  /**
   * Cards field in *BenefitsGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits_grid.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<BenefitsGridSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for BenefitsGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BenefitsGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BenefitsGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BenefitsGrid*
 */
type BenefitsGridSliceVariation = BenefitsGridSliceDefault;

/**
 * BenefitsGrid Shared Slice
 *
 * - **API ID**: `benefits_grid`
 * - **Description**: BenefitsGrid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BenefitsGridSlice = prismic.SharedSlice<
  "benefits_grid",
  BenefitsGridSliceVariation
>;

/**
 * Primary content in *ContactSection → Default → Primary*
 */
export interface ContactSectionSliceDefaultPrimary {
  /**
   * Headline field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Copy field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copy: prismic.RichTextField;
}

/**
 * Default variation for ContactSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactSection*
 */
type ContactSectionSliceVariation = ContactSectionSliceDefault;

/**
 * ContactSection Shared Slice
 *
 * - **API ID**: `contact_section`
 * - **Description**: ContactSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSectionSlice = prismic.SharedSlice<
  "contact_section",
  ContactSectionSliceVariation
>;

/**
 * Primary content in *EdiExpertise → Default → Primary*
 */
export interface EdiExpertiseSliceDefaultPrimary {
  /**
   * Headline field in *EdiExpertise → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: edi_expertise.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Copy field in *EdiExpertise → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: edi_expertise.default.primary.copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copy: prismic.RichTextField;
}

/**
 * Default variation for EdiExpertise Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EdiExpertiseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EdiExpertiseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EdiExpertise*
 */
type EdiExpertiseSliceVariation = EdiExpertiseSliceDefault;

/**
 * EdiExpertise Shared Slice
 *
 * - **API ID**: `edi_expertise`
 * - **Description**: EdiExpertise
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EdiExpertiseSlice = prismic.SharedSlice<
  "edi_expertise",
  EdiExpertiseSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → logos*
 */
export interface HeroSliceDefaultPrimaryLogosItem {
  /**
   * Logo field in *Hero → Default → Primary → logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.logos[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Name field in *Hero → Default → Primary → logos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.logos[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Topline field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Fast | Scalable | Successful
   * - **API ID Path**: hero.default.primary.topline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  topline: prismic.KeyTextField;

  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Copy field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copy: prismic.RichTextField;

  /**
   * cta_primary field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_primary
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_primary: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * cta_secondary field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_secondary
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_secondary: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * widget_menu field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.widget_menu
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  widget_menu: prismic.ImageField<never>;

  /**
   * widget_inventory field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.widget_inventory
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  widget_inventory: prismic.ImageField<never>;

  /**
   * widget_video field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.widget_video
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  widget_video: prismic.ImageField<never>;

  /**
   * logos field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  logos: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryLogosItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *PartnerProgram → Default → Primary → Cards*
 */
export interface PartnerProgramSliceDefaultPrimaryCardsItem {
  /**
   * image field in *PartnerProgram → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_program.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Headline field in *PartnerProgram → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_program.default.primary.cards[].headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Copy field in *PartnerProgram → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_program.default.primary.cards[].copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copy: prismic.RichTextField;
}

/**
 * Primary content in *PartnerProgram → Default → Primary*
 */
export interface PartnerProgramSliceDefaultPrimary {
  /**
   * Topline field in *PartnerProgram → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_program.default.primary.topline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  topline: prismic.KeyTextField;

  /**
   * Headline field in *PartnerProgram → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_program.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Copy field in *PartnerProgram → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_program.default.primary.copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copy: prismic.RichTextField;

  /**
   * Cards field in *PartnerProgram → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_program.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<PartnerProgramSliceDefaultPrimaryCardsItem>
  >;
}

/**
 * Default variation for PartnerProgram Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnerProgramSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnerProgramSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PartnerProgram*
 */
type PartnerProgramSliceVariation = PartnerProgramSliceDefault;

/**
 * PartnerProgram Shared Slice
 *
 * - **API ID**: `partner_program`
 * - **Description**: PartnerProgram
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnerProgramSlice = prismic.SharedSlice<
  "partner_program",
  PartnerProgramSliceVariation
>;

/**
 * Primary content in *QuoteBanner → Default → Primary*
 */
export interface QuoteBannerSliceDefaultPrimary {
  /**
   * quote field in *QuoteBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote_banner.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;
}

/**
 * Default variation for QuoteBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuoteBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuoteBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *QuoteBanner*
 */
type QuoteBannerSliceVariation = QuoteBannerSliceDefault;

/**
 * QuoteBanner Shared Slice
 *
 * - **API ID**: `quote_banner`
 * - **Description**: QuoteBanner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuoteBannerSlice = prismic.SharedSlice<
  "quote_banner",
  QuoteBannerSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PartnerPageDocument,
      PartnerPageDocumentData,
      PartnerPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BenefitsGridSlice,
      BenefitsGridSliceDefaultPrimaryCardsItem,
      BenefitsGridSliceDefaultPrimary,
      BenefitsGridSliceVariation,
      BenefitsGridSliceDefault,
      ContactSectionSlice,
      ContactSectionSliceDefaultPrimary,
      ContactSectionSliceVariation,
      ContactSectionSliceDefault,
      EdiExpertiseSlice,
      EdiExpertiseSliceDefaultPrimary,
      EdiExpertiseSliceVariation,
      EdiExpertiseSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryLogosItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      PartnerProgramSlice,
      PartnerProgramSliceDefaultPrimaryCardsItem,
      PartnerProgramSliceDefaultPrimary,
      PartnerProgramSliceVariation,
      PartnerProgramSliceDefault,
      QuoteBannerSlice,
      QuoteBannerSliceDefaultPrimary,
      QuoteBannerSliceVariation,
      QuoteBannerSliceDefault,
    };
  }
}
