// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic"

export const components = {
  benefits_grid: dynamic(() => import("./BenefitsGrid")),
  contact_section: dynamic(() => import("./ContactSection")),
  edi_expertise: dynamic(() => import("./EdiExpertise")),
  hero: dynamic(() => import("./Hero")),
  partner_program: dynamic(() => import("./PartnerProgram")),
  quote_banner: dynamic(() => import("./QuoteBanner")),
}
